#!/usr/bin/env bash
# clean-code-refactor installer (macOS/Linux; bash 3.2+, no jq dependency).
#
# Target tables below are kept in parity with integrations/registry.json;
# scripts/validate-skill.ps1 fails when the two drift apart.
#
# Exit codes:
#   0 = all requested targets installed/updated or intentionally skipped
#   1 = one or more targets failed
#   2 = usage error, missing source, or preflight abort (nothing was written)

set -euo pipefail

PKG_VERSION='1.4.0'
SKILL_FILE='SKILL.md'
REFERENCE_DIR='references'
# PKG_VERSION, TOOL_SOURCES, known_ids, and the *_TARGETS tables are generated from
# integrations/registry.json by scripts/sync-bash-installer.ps1; do not edit them by hand.
TOOL_SOURCES=('scripts/profile-repository.ps1' 'scripts/profile-repository.sh' 'scripts/check-policy.ps1')
REFERENCES_DIR_NAME='clean-code-refactor-references'
TOOLS_DIR_NAME='clean-code-refactor-tools'
RECEIPT_FILE='.clean-code-refactor-install.json'
POINTER_MARKER='<!-- clean-code-refactor-skill -->'
GENERATED_MARKER="<!-- clean-code-refactor $PKG_VERSION; generated by the package installer; edits here are overwritten on upgrade -->"

usage() {
  cat <<'USAGE_EOF'
Usage: scripts/install.sh [options]

Options:
  -e, --editor NAME     Target id, comma/space list, or 'all' (every target for the
                        scope) or 'detected' (editors already configured on this machine).
                        Ids: agents, cursor, copilot, claude, codex, windsurf, cline,
                        roo, continue, amazonq, opencode, kilo.
  -t, --target PATH     Target project directory (default: current directory).
      --scope SCOPE     'project' (default) or 'user' (per-user global install where
                        the registry declares it).
      --codex-home PATH Codex home directory (default: $CODEX_HOME or ~/.codex).
      --user-home PATH  User home for user-scope targets (default: $HOME; override for
                        tests or portable installs).
      --dry-run         Print the plan without writing anything (alias: --whatif).
  -f, --force           Replace this skill's previously installed files, including
                        user-modified owned files.
      --list            List registry targets and exit.
      --json            Machine-readable JSON plan/result output.
      --verify          Read-only check of installed targets: every owned file matches
                        its receipt and the package, and the version is current.
                        Exit 1 if any target is modified, outdated, or unmanaged.
      --expect-version V
                        With --verify, require installed version V instead of this
                        package's version (for pinned fleets).
      --policy FILE     Organization policy (JSON) to install next to the skill as
                        policy.json. Validated with scripts/check-policy.ps1 when
                        PowerShell is available. Later runs without --policy keep it.
  -h, --help            Show this help.

Exit codes: 0 = success (skips allowed), 1 = target failure, 2 = usage/preflight error.
USAGE_EOF
}

# id|kind|root|path|format|pointer_file|pointer_link|config_file|config_entry|hints|verification
PROJECT_TARGETS=$(cat <<'PROJECT_TARGETS_EOF'
agents|skill-folder|project|.agents/skills/clean-code-refactor|-|AGENTS.md|.agents/skills/clean-code-refactor/SKILL.md|-|-|project:.agents,project:AGENTS.md|-
cursor|rule-file|project|.cursor/rules/clean-code-refactor.mdc|cursor|-|-|-|-|project:.cursor,home:.cursor|-
copilot|skill-folder|project|.github/skills/clean-code-refactor|-|.github/copilot-instructions.md|.github/skills/clean-code-refactor/SKILL.md|-|-|project:.github|-
claude|skill-folder|project|.claude/skills/clean-code-refactor|-|-|-|-|-|project:.claude,home:.claude|-
windsurf|rule-file|project|.windsurf/rules/clean-code-refactor.md|plain|-|-|-|-|project:.windsurf,home:.codeium|-
cline|rule-file|project|.clinerules/clean-code-refactor.md|plain|-|-|-|-|project:.clinerules|-
roo|rule-file|project|.roo/rules/clean-code-refactor.md|plain|-|-|-|-|project:.roo|-
continue|rule-file|project|.continue/rules/clean-code-refactor.md|continue|-|-|-|-|project:.continue|-
amazonq|rule-file|project|.amazonq/rules/clean-code-refactor.md|plain|-|-|-|-|project:.amazonq|-
opencode|skill-folder|project|.opencode/skills/clean-code-refactor|-|-|-|-|-|project:.opencode,xdg-config:opencode|-
kilo|rule-file|project|.kilo/rules/clean-code-refactor.md|plain|-|-|kilo.jsonc|.kilo/rules/clean-code-refactor.md|project:.kilo,project:kilo.jsonc|-
PROJECT_TARGETS_EOF
)

USER_TARGETS=$(cat <<'USER_TARGETS_EOF'
agents|skill-folder|home|.agents/skills/clean-code-refactor|-|-|-|-|-|home:.agents|-
cursor|skill-folder|home|.cursor/skills/clean-code-refactor|-|-|-|-|-|home:.cursor|verify-against-docs
copilot|skill-folder|home|.copilot/skills/clean-code-refactor|-|-|-|-|-|home:.copilot|verify-against-docs
claude|skill-folder|home|.claude/skills/clean-code-refactor|-|-|-|-|-|home:.claude|verify-against-docs
codex|skill-folder|codex-home|skills/clean-code-refactor|-|-|-|-|-|codex-home:skills|-
opencode|skill-folder|xdg-config|opencode/skills/clean-code-refactor|-|-|-|-|-|xdg-config:opencode|verify-against-docs
USER_TARGETS_EOF
)

editors=()
target_path="$(pwd)"
scope='project'
codex_home="${CODEX_HOME:-$HOME/.codex}"
user_home="$HOME"
dry_run=0
force=0
list_only=0
json_out=0
policy_file=""
verify_mode=0
expect_version=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -e|--editor) editors+=("$2"); shift 2 ;;
    -t|--target) target_path="$2"; shift 2 ;;
    --scope) scope="$2"; shift 2 ;;
    --codex-home) codex_home="$2"; shift 2 ;;
    --user-home) user_home="$2"; shift 2 ;;
    --dry-run|--whatif) dry_run=1; shift ;;
    -f|--force) force=1; shift ;;
    --list) list_only=1; shift ;;
    --json) json_out=1; shift ;;
    --verify) verify_mode=1; shift ;;
    --expect-version) [ $# -ge 2 ] || { echo "Error: --expect-version needs a version." >&2; exit 2; }; expect_version="$2"; shift 2 ;;
    --policy) [ $# -ge 2 ] || { echo "Error: --policy needs a file." >&2; exit 2; }; policy_file="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

fail_usage() {
  echo "Error: $1" >&2
  exit 2
}

if [ -n "$expect_version" ]; then
  [ "$verify_mode" -eq 1 ] || fail_usage "--expect-version requires --verify."
  [[ "$expect_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail_usage "--expect-version must be MAJOR.MINOR.PATCH."
fi
if [ "$verify_mode" -eq 1 ]; then
  [ "$dry_run" -eq 0 ] || fail_usage "--verify is read-only; do not combine it with --dry-run."
  force=0
fi

[[ "$scope" == "project" || "$scope" == "user" ]] || fail_usage "Unknown scope: $scope"

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
skill_source="$repository_root/$SKILL_FILE"
reference_source="$repository_root/$REFERENCE_DIR"

resolve_dir() {
  if [ -e "$1" ]; then (cd "$1" && pwd -P); else printf '%s' "$1"; fi
}

if [ "$list_only" -eq 1 ]; then
  if [ "$json_out" -eq 1 ]; then
    printf '{ "package": "%s", "targets": [\n' "$PKG_VERSION"
    first=1
    while IFS='|' read -r id _kind root path _fmt _pf _pl _cf _ce _hints verify; do
      [ -z "$id" ] && continue
      [ "$verify" = "-" ] && verify=""
      [ $first -eq 1 ] || printf ',\n'
      first=0
      printf '  { "editor": "%s", "scope": "project", "kind": "%s", "root": "%s", "path": "%s", "verification": "%s" }' \
        "$id" "$_kind" "$root" "$path" "$verify"
    done <<< "$PROJECT_TARGETS"
    while IFS='|' read -r id _kind root path _fmt _pf _pl _cf _ce _hints verify; do
      [ -z "$id" ] && continue
      [ "$verify" = "-" ] && verify=""
      [ $first -eq 1 ] || printf ',\n'
      first=0
      printf '  { "editor": "%s", "scope": "user", "kind": "%s", "root": "%s", "path": "%s", "verification": "%s" }' \
        "$id" "$_kind" "$root" "$path" "$verify"
    done <<< "$USER_TARGETS"
    printf '\n] }\n'
  else
    echo "Registered targets (package version $PKG_VERSION):"
    while IFS='|' read -r id _kind root path _fmt _pf _pl _cf _ce _hints verify; do
      [ -z "$id" ] && continue
      suffix=""
      [ "$verify" != "-" ] && suffix=" [$verify]"
      printf '  %-10s %-7s %-12s %s%s\n' "$id" project "$root" "$path" "$suffix"
    done <<< "$PROJECT_TARGETS"
    while IFS='|' read -r id _kind root path _fmt _pf _pl _cf _ce _hints verify; do
      [ -z "$id" ] && continue
      suffix=""
      [ "$verify" != "-" ] && suffix=" [$verify]"
      printf '  %-10s %-7s %-12s %s%s\n' "$id" user "$root" "$path" "$suffix"
    done <<< "$USER_TARGETS"
  fi
  exit 0
fi

if [ "$scope" = "project" ]; then
  [ -d "$target_path" ] || fail_usage "Target project directory does not exist: $target_path"
  project_root="$(cd "$target_path" && pwd -P)"
else
  project_root=""
fi

codex_home="$(resolve_dir "$codex_home")"
home_root="$(resolve_dir "$user_home")"
xdg_config_root="$(resolve_dir "${XDG_CONFIG_HOME:-$user_home/.config}")"

root_for() {
  case "$1" in
    project) printf '%s' "$project_root" ;;
    codex-home) printf '%s' "$codex_home" ;;
    home) printf '%s' "$home_root" ;;
    xdg-config) printf '%s' "$xdg_config_root" ;;
    *) return 1 ;;
  esac
}

join_under_root() {
  local root="$1" relative="$2"
  case "$relative" in
    *..*) fail_usage "Registry path must not contain '..': $relative" ;;
  esac
  printf '%s/%s' "${root%/}" "$relative"
}

path_under_root() {
  local prefix="${1%/}/"
  case "$2" in
    "$prefix"*) return 0 ;;
    *) return 1 ;;
  esac
}

first_reparse_between() {
  # Echo the first symlinked component between root and destination, if any.
  local root="${1%/}" dest="$2" rel current seg oldifs
  if ! path_under_root "$root" "$dest"; then
    printf '%s' "$dest"
    return 0
  fi
  rel="${dest#"$root"/}"
  current="$root"
  oldifs="$IFS"
  IFS='/'
  for seg in $rel; do
    current="$current/$seg"
    if [ -L "$current" ]; then
      IFS="$oldifs"
      printf '%s' "$current"
      return 0
    fi
  done
  IFS="$oldifs"
  return 1
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  elif command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 -r "$1" | cut -d' ' -f1
  else
    printf ''
  fi
}

json_escape() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '%s' "$s"
}

# --------------------------- source inventory ------------------------------

for required in "$skill_source" "$reference_source"; do
  [ -e "$required" ] || fail_usage "Required source is missing: $required"
done
for tool in "${TOOL_SOURCES[@]}"; do
  [ -f "$repository_root/$tool" ] || fail_usage "Required source is missing: $repository_root/$tool"
done

SOURCE_RELS=()
SOURCE_RELS+=("$SKILL_FILE")
while IFS= read -r -d '' f; do
  SOURCE_RELS+=("$REFERENCE_DIR/${f#"$reference_source"/}")
done < <(find "$reference_source" -type f -print0)
for tool in "${TOOL_SOURCES[@]}"; do SOURCE_RELS+=("$tool"); done

# Organization policy: validated before anything is written.
policy_source=""
policy_hash=""
if [ -n "$policy_file" ]; then
  [ -f "$policy_file" ] || fail_usage "Policy file not found: $policy_file"
  [ -L "$policy_file" ] && fail_usage "Policy file must not be a symlink: $policy_file"
  policy_size="$(wc -c < "$policy_file")"
  [ "${policy_size//[!0-9]/}" -le 65536 ] || fail_usage "Policy file is larger than 65536 bytes: $policy_file"
  policy_source="$(cd "$(dirname "$policy_file")" && pwd -P)/$(basename "$policy_file")"
  if command -v pwsh >/dev/null 2>&1; then
    if ! policy_check="$(pwsh -NoProfile -NonInteractive -File "$repository_root/scripts/check-policy.ps1" -PolicyFile "$policy_source" 2>&1)"; then
      fail_usage "Policy file is invalid: $policy_check"
    fi
  else
    echo "Warning: PowerShell is not available, so the policy file was not validated. Run scripts/check-policy.ps1 -PolicyFile on it before relying on it." >&2
  fi
  policy_hash="$(sha256_of "$policy_source")"
fi

# Where an organization policy lives inside an installed unit (check-policy.ps1 looks there).
policy_key_for() {
  if [ "$1" = "rule-file" ]; then printf '%s' "$TOOLS_DIR_NAME/policy.json"; else printf '%s' "policy.json"; fi
}

# --------------------------- rule body generation --------------------------

skill_text="$(cat "$skill_source")"
# References are rewritten once, then each tool path (scripts/x -> clean-code-refactor-tools/x).
tool_rewrites=()
for tool in "${TOOL_SOURCES[@]}"; do
  tool_rewrites+=(-e "s|${tool//./\\.}|$TOOLS_DIR_NAME/${tool##*/}|g")
done
rule_body="$(printf '%s\n' "$skill_text" | awk '
  NR == 1 && /^---$/ { front = 1; next }
  front && /^---$/ { front = 0; next }
  !front { print }
' | sed -e "s|references/|$REFERENCES_DIR_NAME/|g" "${tool_rewrites[@]}")"

validate_rule_links() {
  # Every generated local link must resolve to a real package file (fixes broken rule links).
  local links link rel
  links="$(printf '%s' "$rule_body" | grep -oE "$REFERENCES_DIR_NAME/[A-Za-z0-9][A-Za-z0-9._/-]*" | LC_ALL=C sort -u || true)"
  while IFS= read -r link; do
    [ -z "$link" ] && continue
    rel="${link#"$REFERENCES_DIR_NAME"/}"
    if [ ! -f "$reference_source/$rel" ]; then
      fail_usage "Generated rule references missing package file: $link"
    fi
  done <<< "$links"
}
validate_rule_links

format_rule() {
  local format="$1"
  case "$format" in
    cursor)
      printf '%s\n' '---' \
        'description: Apply clean-code refactoring, hardening, lint remediation, and duplicate detection.' \
        'globs:' \
        'alwaysApply: false' \
        '---' ''
      printf '%s\n\n' "$GENERATED_MARKER"
      printf '%s\n\n' "$rule_body"
      printf '%s\n' "@$REFERENCES_DIR_NAME/language-hardening.md" "@$REFERENCES_DIR_NAME/static-quality-rules.md"
      ;;
    continue)
      printf '%s\n' '---' \
        'name: Clean Code Refactor' \
        'description: Refactor, review, and harden changed code.' \
        'alwaysApply: false' \
        '---' ''
      printf '%s\n\n' "$GENERATED_MARKER"
      printf '%s\n' "$rule_body"
      ;;
    plain)
      printf '%s\n\n' "$GENERATED_MARKER"
      printf '%s\n' "$rule_body"
      ;;
    *) fail_usage "Unsupported rule format: $format" ;;
  esac
}

# --------------------------- receipt helpers -------------------------------

receipt_version() {
  sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1" | head -n 1
}

receipt_hash_for_key() {
  awk -v key="$1" -F'"' '$2 == key && $4 ~ /^[0-9a-fA-F]{64}$/ { print $4; exit }' "$2"
}

receipt_entries() {
  grep -E '^ *"[^"]+": *"[0-9a-fA-F]{64}",?$' "$1" \
    | sed -E 's/^ *"([^"]+)": *"([0-9a-fA-F]{64})",?$/\1\t\2/'
}

RECEIPT_RELS=()

write_receipt() {
  local receipt_path="$1" editor_id="$2" kind="$3"
  local tmp="$receipt_path.tmp.$$" first=1 rel hash
  {
    printf '{\n'
    printf '  "package": "clean-code-refactor",\n'
    printf '  "version": "%s",\n' "$PKG_VERSION"
    printf '  "installedAt": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '  "editor": "%s",\n' "$(json_escape "$editor_id")"
    printf '  "scope": "%s",\n' "$scope"
    printf '  "kind": "%s",\n' "$kind"
    printf '  "files": {\n'
    for rel in "${RECEIPT_RELS[@]}"; do
      hash="$(sha256_of "$(join_under_root "$unit_base" "$rel")")"
      [ $first -eq 1 ] || printf ',\n'
      first=0
      printf '    "%s": "%s"' "$(json_escape "$rel")" "$hash"
    done
    printf '\n  }\n}\n'
  } > "$tmp"
  mv "$tmp" "$receipt_path"
}

# --------------------------- mirrored directory sync -----------------------

SYNC_COPIED=0
SYNC_REMOVED=0
SYNC_FAILED=0

sync_mirror() {
  # Mirror $1 into owned $2: copy new/changed files, remove stale owned files.
  # Unrelated files OUTSIDE owned paths are never touched.
  local src="$1" dst="$2" rel s d
  SYNC_COPIED=0
  SYNC_REMOVED=0
  SYNC_FAILED=0
  while IFS= read -r -d '' f; do
    rel="${f#"$src"/}"
    s="$src/$rel"
    d="$dst/$rel"
    if [ ! -e "$d" ] || ! cmp -s "$s" "$d"; then
      SYNC_COPIED=$((SYNC_COPIED + 1))
      if [ "$dry_run" -eq 0 ]; then
        mkdir -p "$(dirname "$d")"
        if ! cp "$s" "$d.tmp.$$" || ! mv "$d.tmp.$$" "$d" || ! cmp -s "$s" "$d"; then
          rm -f "$d.tmp.$$" 2>/dev/null || true
          echo "Failed to sync reference file: $rel" >&2
          SYNC_FAILED=1
        fi
      fi
    fi
  done < <(find "$src" -type f -print0)
  if [ -d "$dst" ]; then
    while IFS= read -r -d '' f; do
      rel="${f#"$dst"/}"
      if [ ! -e "$src/$rel" ]; then
        SYNC_REMOVED=$((SYNC_REMOVED + 1))
        if [ "$dry_run" -eq 0 ]; then
          rm -f "$dst/$rel" || { echo "Failed to remove stale file: $rel" >&2; SYNC_FAILED=1; }
        fi
      fi
    done < <(find "$dst" -type f -print0)
    if [ "$dry_run" -eq 0 ]; then
      find "$dst" -depth -type d -empty -exec rmdir {} \; 2>/dev/null || true
    fi
  fi
}

copy_file_verified() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst.tmp.$$"
  mv "$dst.tmp.$$" "$dst"
  if ! cmp -s "$src" "$dst"; then
    echo "Post-copy verification failed for $dst" >&2
    return 1
  fi
}

write_file_if_changed() {
  # Returns 0 when the file was written, 1 when unchanged.
  local dst="$1" tmp
  local content="$2"
  if [ -f "$dst" ] && printf '%s' "$content" | cmp -s - "$dst"; then
    return 1
  fi
  mkdir -p "$(dirname "$dst")"
  tmp="$dst.tmp.$$"
  printf '%s' "$content" > "$tmp"
  mv "$tmp" "$dst"
  return 0
}

# --------------------------- selection -------------------------------------

requested=""
if [ "${#editors[@]}" -gt 0 ]; then
  for group in "${editors[@]}"; do
    IFS=',' read -r -a parts <<< "$group"
    for p in "${parts[@]}"; do
      p="$(printf '%s' "$p" | tr -d '[:space:]')"
      [ -z "$p" ] && continue
      case " $requested " in *" $p "*) ;; *) requested="$requested $p" ;; esac
    done
  done
fi
requested="${requested# }"

known_ids="agents cursor copilot claude codex windsurf cline roo continue amazonq opencode kilo"

# Trailing newline is REQUIRED: read drops a final record that lacks one.
table_for_scope() {
  if [ "$scope" = "user" ]; then printf '%s\n' "$USER_TARGETS"; else printf '%s\n' "$PROJECT_TARGETS"; fi
}

if [ -z "$requested" ] || [ "$requested" = "all" ]; then
  selected="$known_ids"
elif [ "$requested" = "detected" ]; then
  selected=""
  while IFS='|' read -r id _kind root path _fmt _pf _pl _cf _ce hints _verify; do
    [ -z "$id" ] && continue
    r="$(root_for "$root")" || r=""
    [ -z "$r" ] && continue
    matched=0
    [ -e "$(join_under_root "$r" "$path")" ] && matched=1
    if [ $matched -eq 0 ]; then
      oldifs="$IFS"; IFS=','
      for hint in $hints; do
        IFS="$oldifs"
        [ "$hint" = "-" ] && continue
        hroot="${hint%%:*}"
        hpath="${hint#*:}"
        hr="$(root_for "$hroot")" || hr=""
        [ -z "$hr" ] && continue
        if [ -e "$(join_under_root "$hr" "$hpath")" ]; then matched=1; break; fi
      done
      IFS="$oldifs"
    fi
    [ $matched -eq 1 ] && selected="$selected $id"
  done < <(table_for_scope)
  selected="${selected# }"
  if [ -z "$selected" ]; then
    echo "No installed editors detected for scope '$scope'. Nothing to do."
    exit 0
  fi
else
  for id in $requested; do
    case " $known_ids " in
      *" $id "*) ;;
      *) fail_usage "Unknown editor target: '$id'. Known targets: $known_ids" ;;
    esac
  done
  selected="$requested"
fi

# --------------------------- plan ------------------------------------------

declare -a P_ID P_KIND P_ROOT P_PATH P_FORMAT P_POINTER_FILE P_POINTER_LINK P_CONFIG_FILE P_CONFIG_ENTRY P_VERIFY P_UNIT_BASE P_RECEIPT P_STATUS P_REASON
plan_count=0

while IFS='|' read -r id kind root path fmt pointer_file pointer_link config_file config_entry hints verify; do
  [ -z "$id" ] && continue
  case " $selected " in
    *" $id "*) ;;
    *) continue ;;
  esac

  r="$(root_for "$root")" || r=""
  destination=""
  unit_base=""
  receipt=""
  if [ -z "$r" ]; then
    status="failed"; reason="root '$root' is unavailable"
  else
    destination="$(join_under_root "$r" "$path")"
    unit_base="$destination"
    if [ "$kind" = "rule-file" ]; then
      unit_base="$(dirname "$destination")"
    fi
    receipt="$unit_base/$RECEIPT_FILE"
    if [ "$kind" = "rule-file" ]; then
      receipt="$unit_base/$TOOLS_DIR_NAME/$RECEIPT_FILE"
    fi
  fi

  status=""
  reason=""
  if [ -n "$r" ]; then
    if ! path_under_root "$r" "$destination"; then
      status="failed"; reason="destination escapes its root: $destination"
    elif reparse="$(first_reparse_between "$r" "$destination")"; then
      status="failed"; reason="refusing to traverse symlink/reparse point: $reparse"
    else
      unit_exists=0
      if [ "$kind" = "rule-file" ]; then
        [ -f "$destination" ] && unit_exists=1
      else
        [ -d "$destination" ] && unit_exists=1
      fi

      if [ $unit_exists -eq 0 ]; then
        status="install"
      elif [ ! -f "$receipt" ]; then
        if [ "$force" -eq 1 ]; then
          status="update"; reason="existing unmanaged install; replacing because --force was given"
        else
          status="skipped"; reason="existing install has no package receipt (unmanaged); use --force to replace"
        fi
      else
        unit_user_modified=0
        while IFS=$'\t' read -r key hash; do
          [ -z "$key" ] && continue
          f="$unit_base/$key"
          if [ ! -f "$f" ]; then
            unit_user_modified=1
          else
            h="$(sha256_of "$f")"
            if [ -n "$h" ] && [ "$h" != "$hash" ]; then unit_user_modified=1; fi
          fi
        done < <(receipt_entries "$receipt")

        if [ $unit_user_modified -eq 1 ]; then
          if [ "$force" -eq 1 ]; then
            status="update"; reason="user modifications detected; replacing because --force was given"
          else
            status="skipped"; reason="user modifications detected; use --force to overwrite"
          fi
        else
          unit_current=1
          for rel in "${SOURCE_RELS[@]}"; do
            key="$rel"
            if [ "$kind" = "rule-file" ]; then
              case "$key" in
                "$SKILL_FILE")
                  # The rule file is generated, so compare it with what this run would write.
                  if ! printf '%s\n' "$(format_rule "$fmt")" | cmp -s - "$destination"; then unit_current=0; break; fi
                  continue ;;
                scripts/*) key="$TOOLS_DIR_NAME/${key##*/}" ;;
                "$REFERENCE_DIR"/*) key="$REFERENCES_DIR_NAME/${key#"$REFERENCE_DIR"/}" ;;
              esac
            fi
            disk_hash="$(sha256_of "$repository_root/$rel")"
            if [ -z "$disk_hash" ] || [ "$disk_hash" != "$(receipt_hash_for_key "$key" "$receipt")" ]; then
              unit_current=0
              break
            fi
          done
          if [ $unit_current -eq 1 ] && [ -n "$policy_hash" ]; then
            policy_installed="$unit_base/$(policy_key_for "$kind")"
            if [ ! -f "$policy_installed" ] || [ "$(sha256_of "$policy_installed")" != "$policy_hash" ]; then unit_current=0; fi
          fi
          if [ $unit_current -eq 1 ] && [ "$(receipt_version "$receipt")" = "$PKG_VERSION" ]; then
            status="up-to-date"
          else
            status="update"
            rv="$(receipt_version "$receipt")"
            if [ -n "$rv" ] && [ "$rv" != "$PKG_VERSION" ]; then
              reason="upgrading receipt version $rv -> $PKG_VERSION"
            fi
          fi
        fi
      fi
    fi
  fi

  if [ -z "$status" ]; then status="failed"; reason="unhandled planning state"; fi

  P_ID+=("$id"); P_STATUS+=("$status"); P_REASON+=("$reason"); P_UNIT_BASE+=("$unit_base"); P_ROOT+=("$r")
  P_KIND+=("$kind"); P_PATH+=("$path"); P_FORMAT+=("$fmt"); P_POINTER_FILE+=("$pointer_file")
  P_POINTER_LINK+=("$pointer_link"); P_CONFIG_FILE+=("$config_file"); P_CONFIG_ENTRY+=("$config_entry")
  P_VERIFY+=("$verify"); P_RECEIPT+=("$receipt")
  plan_count=$((plan_count + 1))
done < <(table_for_scope)

# Requested targets that declare no entry for this scope (e.g. codex in project scope).
for id in $selected; do
  found=0
  while IFS='|' read -r tid _rest; do
    if [ "$tid" = "$id" ]; then found=1; fi
  done < <(table_for_scope)
  if [ $found -eq 0 ]; then
    P_ID+=("$id"); P_STATUS+=("skipped")
    P_REASON+=("scope '$scope' is not declared for this editor (see docs/ide-compatibility.md)")
    P_UNIT_BASE+=(""); P_ROOT+=(""); P_KIND+=(""); P_PATH+=(""); P_FORMAT+=("")
    P_POINTER_FILE+=(""); P_POINTER_LINK+=(""); P_CONFIG_FILE+=(""); P_CONFIG_ENTRY+=("")
    P_VERIFY+=(""); P_RECEIPT+=("")
    plan_count=$((plan_count + 1))
  fi
done

# --------------------------- verify (read-only) ----------------------------
# Reuses the plan: "up-to-date" already means every owned file matches its receipt and
# the package. Nothing below writes.
if [ "$verify_mode" -eq 1 ]; then
  expected_version="${expect_version:-$PKG_VERSION}"
  explicit=1
  case "$requested" in ""|all|detected) explicit=0 ;; esac
  verify_failed=0
  VERIFY_LINES=()
  for i in $(seq 0 $((plan_count - 1))); do
    vstatus=""; vreason="${P_REASON[$i]}"; installed_version=""; vdest=""
    if [ -n "${P_RECEIPT[$i]}" ] && [ -f "${P_RECEIPT[$i]}" ]; then installed_version="$(receipt_version "${P_RECEIPT[$i]}")"; fi
    if [ -n "${P_ROOT[$i]}" ]; then vdest="$(join_under_root "${P_ROOT[$i]}" "${P_PATH[$i]}")"; fi
    case "${P_STATUS[$i]}" in
      failed) vstatus="failed" ;;
      install) vstatus="not-installed"; vreason="" ;;
      up-to-date) vstatus="verified"; vreason="" ;;
      update) vstatus="outdated"; vreason="installed files or version ${installed_version:-unknown} differ from package $PKG_VERSION" ;;
      skipped)
        case "$vreason" in
          *"no package receipt"*) vstatus="unmanaged"; vreason="installed files have no package receipt" ;;
          *"user modifications"*) vstatus="modified"; vreason="an owned file is missing or differs from its receipt" ;;
          *) vstatus="not-applicable" ;;
        esac ;;
    esac
    # Pinned to another version: the package cannot vouch for those files, so check the
    # receipt integrity (above) and the version only.
    if [ "$expected_version" != "$PKG_VERSION" ] && { [ "$vstatus" = "verified" ] || [ "$vstatus" = "outdated" ]; }; then
      if [ "$installed_version" = "$expected_version" ]; then vstatus="verified"; vreason="integrity and version checked; content not compared with package $PKG_VERSION"
      else vstatus="outdated"; vreason="installed version ${installed_version:-unknown}, expected $expected_version"; fi
    fi
    case "$vstatus" in
      verified|not-applicable) ;;
      not-installed) if [ $explicit -eq 1 ]; then verify_failed=1; fi ;;
      *) verify_failed=1 ;;
    esac
    if [ "$json_out" -eq 1 ]; then
      VERIFY_LINES+=("{ \"editor\": \"$(json_escape "${P_ID[$i]}")\", \"scope\": \"$scope\", \"status\": \"$vstatus\", \"destination\": \"$(json_escape "$vdest")\", \"installedVersion\": \"$(json_escape "$installed_version")\", \"reason\": \"$(json_escape "$vreason")\" }")
    else
      line="[$vstatus] ${P_ID[$i]} ($scope)"
      if [ -n "$vdest" ]; then line="$line -> $vdest"; fi
      if [ -n "$vreason" ]; then line="$line - $vreason"; fi
      echo "$line"
    fi
  done
  if [ "$json_out" -eq 1 ]; then
    passed_json="true"; [ $verify_failed -eq 1 ] && passed_json="false"
    printf '{ "mode": "verify", "package": "%s", "expectedVersion": "%s", "scope": "%s", "passed": %s, "results": [\n' "$PKG_VERSION" "$(json_escape "$expected_version")" "$scope" "$passed_json"
    first=1
    for entry in ${VERIFY_LINES[@]+"${VERIFY_LINES[@]}"}; do
      [ $first -eq 1 ] || printf ',\n'
      first=0
      printf '%s' "$entry"
    done
    printf '\n] }\n'
  else
    if [ $verify_failed -eq 1 ]; then echo "Verification failed."; else echo "Verification passed."; fi
  fi
  exit $verify_failed
fi

blocked=0
for i in $(seq 0 $((plan_count - 1))); do
  if [ "${P_STATUS[$i]}" = "failed" ]; then blocked=$((blocked + 1)); fi
done
if [ $blocked -gt 0 ] && [ "$dry_run" -eq 0 ]; then
  for i in $(seq 0 $((plan_count - 1))); do
    if [ "${P_STATUS[$i]}" = "failed" ]; then
      echo "Preflight failed for ${P_ID[$i]}: ${P_REASON[$i]}" >&2
    fi
  done
  echo "Error: preflight failed for one or more targets; nothing was written." >&2
  exit 2
fi

# --------------------------- execute ---------------------------------------

RESULT_LINES=()
count_installed=0; count_updated=0; count_uptodate=0; count_skipped=0; count_failed=0

emit_result() {
  local editor="$1" status="$2" destination="$3" reason="${4:-}" written="${5:-0}" removed="${6:-0}"
  if [ "$json_out" -eq 1 ]; then
    RESULT_LINES+=("{ \"editor\": \"$(json_escape "$editor")\", \"scope\": \"$scope\", \"status\": \"$status\", \"destination\": \"$(json_escape "$destination")\", \"reason\": \"$(json_escape "$reason")\", \"filesWritten\": $written, \"filesRemoved\": $removed }")
  else
    local line="[$status] $editor ($scope) -> $destination"
    if [ -n "$reason" ]; then line="$line - $reason"; fi
    if [ "$written" -gt 0 ]; then line="$line [files written: $written]"; fi
    if [ "$removed" -gt 0 ]; then line="$line [stale removed: $removed]"; fi
    echo "$line"
  fi
  case "$status" in
    installed) count_installed=$((count_installed + 1)) ;;
    updated) count_updated=$((count_updated + 1)) ;;
    up-to-date) count_uptodate=$((count_uptodate + 1)) ;;
    skipped) count_skipped=$((count_skipped + 1)) ;;
    failed) count_failed=$((count_failed + 1)) ;;
  esac
}

# Human-readable progress; goes to stderr in --json mode so stdout stays parseable.
progress() {
  if [ "$json_out" -eq 1 ]; then echo "$1" >&2; else echo "$1"; fi
}

install_pointer() {
  local pointer_path="$1" skill_link="$2" body create_body
  create_body="$POINTER_MARKER"$'\n## Clean Code Refactor\n\nFor refactoring, lint remediation, duplicate detection, code hardening, and code-quality reviews, load and follow `'"$skill_link"$'`.\n<!-- /clean-code-refactor-skill -->\n'
  body=$'\n\n'"$create_body"
  if [ ! -e "$pointer_path" ]; then
    mkdir -p "$(dirname "$pointer_path")"
    printf '%s' "$create_body" > "$pointer_path"
    progress "Created pointer: $pointer_path"
  elif ! grep -Fq "$POINTER_MARKER" "$pointer_path"; then
    printf '%s' "$body" >> "$pointer_path"
    progress "Appended pointer section: $pointer_path"
  fi
}

ensure_config_entry() {
  local config_path="$1" config_entry="$2"
  if [ ! -e "$config_path" ]; then
    mkdir -p "$(dirname "$config_path")"
    printf '{\n  "instructions": [\n    "%s"\n  ]\n}\n' "$config_entry" > "$config_path"
    progress "Created configuration: $config_path"
  elif ! grep -Fq "$config_entry" "$config_path"; then
    echo "Add \"$config_entry\" to the instructions array in $config_path to enable this rule." >&2
  fi
}

ensure_additive_extras() {
  # Pointer sections and config entries are additive and marked; re-check them even
  # when the owned unit itself is already up to date (a user may have removed them).
  local kind="$1" root="$2" pointer_file="$3" pointer_link="$4" config_file="$5" config_entry="$6"
  [ "$dry_run" -eq 1 ] && return 0
  if [ "$kind" = "skill-folder" ] && [ "$pointer_file" != "-" ] && [ -n "$pointer_file" ]; then
    install_pointer "$(join_under_root "$root" "$pointer_file")" "$pointer_link"
  fi
  if [ "$kind" = "rule-file" ] && [ "$config_file" != "-" ] && [ -n "$config_file" ]; then
    ensure_config_entry "$(join_under_root "$root" "$config_file")" "$config_entry"
  fi
}

for i in $(seq 0 $((plan_count - 1))); do
  id="${P_ID[$i]}"; status="${P_STATUS[$i]}"; reason="${P_REASON[$i]}"
  unit_base="${P_UNIT_BASE[$i]}"; root="${P_ROOT[$i]}"; kind="${P_KIND[$i]}"
  receipt="${P_RECEIPT[$i]}"
  fmt="${P_FORMAT[$i]}"; pointer_file="${P_POINTER_FILE[$i]}"; pointer_link="${P_POINTER_LINK[$i]}"
  config_file="${P_CONFIG_FILE[$i]}"; config_entry="${P_CONFIG_ENTRY[$i]}"; verify="${P_VERIFY[$i]}"

  if [ -z "$unit_base" ]; then
    emit_result "$id" "$status" "" "$reason" 0 0
    continue
  fi
  destination="$(join_under_root "$root" "${P_PATH[$i]}")"

  if [ "$status" = "skipped" ] || [ "$status" = "failed" ]; then
    emit_result "$id" "$status" "$destination" "$reason" 0 0
    continue
  fi

  if [ "$status" = "up-to-date" ]; then
    # Owned files already match the package; still re-check additive pointer/config extras.
    ensure_additive_extras "$kind" "$root" "$pointer_file" "$pointer_link" "$config_file" "$config_entry"
    emit_result "$id" "$status" "$destination" "$reason" 0 0
    continue
  fi

  written=0
  removed=0
  target_failed=0

  if [ "$kind" = "skill-folder" ]; then
    if [ "$dry_run" -eq 0 ]; then
      # Copy byte-for-byte: capturing the text with $(...) would drop the final newline.
      if ! cmp -s "$skill_source" "$unit_base/$SKILL_FILE"; then
        if copy_file_verified "$skill_source" "$unit_base/$SKILL_FILE"; then written=$((written + 1)); else target_failed=1; fi
      fi
    fi
    sync_mirror "$reference_source" "$unit_base/$REFERENCE_DIR"
    if [ $SYNC_FAILED -eq 1 ]; then target_failed=1; fi
    written=$((written + SYNC_COPIED))
    removed=$((removed + SYNC_REMOVED))
    for tool in "${TOOL_SOURCES[@]}"; do
      if [ "$dry_run" -eq 0 ]; then
        if ! copy_file_verified "$repository_root/$tool" "$unit_base/$tool"; then target_failed=1; fi
      fi
      written=$((written + 1))
    done
    if [ $target_failed -eq 0 ]; then
      ensure_additive_extras "$kind" "$root" "$pointer_file" "$pointer_link" "-" "-"
    fi
  else
    if [ "$dry_run" -eq 0 ]; then
      # $(...) drops the final newline; add it back so both installers write identical files.
      if write_file_if_changed "$destination" "$(format_rule "$fmt")"$'\n'; then written=$((written + 1)); fi
    fi
    sync_mirror "$reference_source" "$unit_base/$REFERENCES_DIR_NAME"
    if [ $SYNC_FAILED -eq 1 ]; then target_failed=1; fi
    written=$((written + SYNC_COPIED))
    removed=$((removed + SYNC_REMOVED))
    for tool in "${TOOL_SOURCES[@]}"; do
      if [ "$dry_run" -eq 0 ]; then
        if ! copy_file_verified "$repository_root/$tool" "$unit_base/$TOOLS_DIR_NAME/${tool##*/}"; then target_failed=1; fi
      fi
      written=$((written + 1))
    done
    if [ $target_failed -eq 0 ]; then
      ensure_additive_extras "$kind" "$root" "-" "-" "$config_file" "$config_entry"
    fi
  fi

  policy_key="$(policy_key_for "$kind")"
  if [ -n "$policy_source" ]; then
    if [ "$dry_run" -eq 0 ]; then
      if ! copy_file_verified "$policy_source" "$unit_base/$policy_key"; then target_failed=1; fi
    fi
    written=$((written + 1))
  fi

  # --------------------------- receipt ---------------------------
  if [ $target_failed -eq 0 ] && [ "$dry_run" -eq 0 ]; then
    RECEIPT_RELS=()
    if [ "$kind" = "skill-folder" ]; then
      for rel in "${SOURCE_RELS[@]}"; do RECEIPT_RELS+=("$rel"); done
    else
      RECEIPT_RELS+=("$(basename "$destination")")
      for tool in "${TOOL_SOURCES[@]}"; do RECEIPT_RELS+=("$TOOLS_DIR_NAME/${tool##*/}"); done
      for rel in "${SOURCE_RELS[@]}"; do
        case "$rel" in
          "$SKILL_FILE"|scripts/*) ;; # already recorded under mapped names
          *) RECEIPT_RELS+=("$REFERENCES_DIR_NAME/${rel#"$REFERENCE_DIR"/}") ;;
        esac
      done
    fi
    # An installed organization policy stays owned until it is replaced.
    if [ -f "$unit_base/$policy_key" ]; then
      if [ -n "$policy_source" ] || { [ -f "$receipt" ] && [ -n "$(receipt_hash_for_key "$policy_key" "$receipt")" ]; }; then
        RECEIPT_RELS+=("$policy_key")
      fi
    fi
    mkdir -p "$(dirname "$receipt")"
    write_receipt "$receipt" "$id" "$kind"
  fi

  if [ $target_failed -eq 1 ]; then
    emit_result "$id" "failed" "$destination" "${reason:-target installation failed}" "$written" "$removed"
  else
    if [ "$status" = "install" ]; then final="installed"; else final="updated"; fi
    if [ "$verify" != "-" ] && [ -n "$verify" ] && [ "$dry_run" -eq 0 ]; then
      echo "Warning: target '$id' user scope is marked '$verify': confirm the destination against your installed editor's documentation." >&2
    fi
    emit_result "$id" "$final" "$destination" "$reason" "$written" "$removed"
  fi
done

if [ "$json_out" -eq 1 ]; then
  dry_json="false"
  [ "$dry_run" -eq 1 ] && dry_json="true"
  printf '{ "package": "%s", "scope": "%s", "dryRun": %s, "results": [\n' "$PKG_VERSION" "$scope" "$dry_json"
  first=1
  for entry in ${RESULT_LINES[@]+"${RESULT_LINES[@]}"}; do
    [ $first -eq 1 ] || printf ',\n'
    first=0
    printf '%s' "$entry"
  done
  printf '\n], "summary": { "installed": %d, "updated": %d, "upToDate": %d, "skipped": %d, "failed": %d } }\n' \
    "$count_installed" "$count_updated" "$count_uptodate" "$count_skipped" "$count_failed"
else
  echo "Summary: installed $count_installed, updated $count_updated, up-to-date $count_uptodate, skipped $count_skipped, failed $count_failed."
  if [ "$dry_run" -eq 1 ]; then echo "Dry run: no files were written."; fi
fi

if [ "$count_failed" -gt 0 ]; then exit 1; fi
exit 0
